# Generated by Django 5.1.3 on 2024-12-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="almacen",
            options={
                "ordering": ["nombre"],
                "verbose_name": "almacen",
                "verbose_name_plural": "almacenes",
            },
        ),
        migrations.AlterModelOptions(
            name="compra",
            options={
                "ordering": ["producto"],
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
            },
        ),
        migrations.AlterModelOptions(
            name="precioproducto",
            options={
                "ordering": ["producto"],
                "verbose_name": "precio-producto",
                "verbose_name_plural": "precios-productos",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["nombre"],
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
            },
        ),
        migrations.AddIndex(
            model_name="almacen",
            index=models.Index(fields=["id"], name="compras_alm_id_bbef01_idx"),
        ),
        migrations.AddIndex(
            model_name="almacen",
            index=models.Index(fields=["nombre"], name="compras_alm_nombre_347c3c_idx"),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["id"], name="compras_com_id_1b41b4_idx"),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["producto"], name="compras_com_product_de9e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["cantidad"], name="compras_com_cantida_9b9242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(fields=["fecha"], name="compras_com_fecha_49ff0e_idx"),
        ),
        migrations.AddIndex(
            model_name="precioproducto",
            index=models.Index(fields=["id"], name="compras_pre_id_f95bdb_idx"),
        ),
        migrations.AddIndex(
            model_name="precioproducto",
            index=models.Index(
                fields=["producto"], name="compras_pre_product_9e5166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precioproducto",
            index=models.Index(fields=["precio"], name="compras_pre_precio_3b600c_idx"),
        ),
        migrations.AddIndex(
            model_name="precioproducto",
            index=models.Index(fields=["fecha"], name="compras_pre_fecha_a77a1e_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["id"], name="compras_pro_id_ee51d2_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="compras_pro_nombre_ac0b59_idx"),
        ),
    ]
