# Generated by Django 5.1.3 on 2024-12-17 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_alter_almacen_options_alter_compra_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="almacen",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="almacen",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="compra",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="compra",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="precioproducto",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="precioproducto",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos_ventas/"),
        ),
        migrations.AddField(
            model_name="producto",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
