# Generated by Django 5.1.3 on 2024-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0005_alter_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="compras/defecto.jpg",
                null=True,
                upload_to="compras/",
            ),
        ),
    ]
