# Generated by Django 5.1.3 on 2024-12-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_productos_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="imagen",
            field=models.ImageField(
                blank=True, default="ventas/defecto.jpg", null=True, upload_to="ventas/"
            ),
        ),
    ]
