# Generated by Django 5.2 on 2025-07-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuenta", models.CharField(max_length=100)),
                ("saldo", models.FloatField()),
                ("un_peso", models.IntegerField(blank=True, default=0, null=True)),
                ("tres_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("cinco_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("diez_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("veinte_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cincuenta_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cien_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "doscientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "quinientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("mil_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cuentas",
                "verbose_name_plural": "cuentas",
                "ordering": ["cuenta"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_cuen_id_7a7487_idx"),
                    models.Index(
                        fields=["cuenta"], name="ventas_cuen_cuenta_cd5991_idx"
                    ),
                    models.Index(
                        fields=["update_at"], name="ventas_cuen_update__fd8703_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cuenta_historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("un_peso", models.IntegerField(blank=True, default=0, null=True)),
                ("tres_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("cinco_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("diez_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("veinte_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cincuenta_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cien_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "doscientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "quinientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("mil_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("saldo", models.FloatField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cuenta_historico",
                "verbose_name_plural": "cuentas_historico",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_cuen_id_0c6ab6_idx"),
                    models.Index(fields=["fecha"], name="ventas_cuen_fecha_3e7e89_idx"),
                    models.Index(fields=["saldo"], name="ventas_cuen_saldo_1f8796_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Departamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departamento", models.CharField(max_length=200)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("punto_de_venta", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "departamento",
                "verbose_name_plural": "departamentos",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_depa_id_46f0dc_idx"),
                    models.Index(
                        fields=["departamento"], name="ventas_depa_departa_cb02f5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="fileUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="ficheros/")),
                ("fecha", models.DateTimeField()),
                ("actualizar", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_file_id_19ee8d_idx"),
                    models.Index(fields=["fecha"], name="ventas_file_fecha_fda7df_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lacteos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Lactetos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_lact_id_203fb4_idx"),
                    models.Index(
                        fields=["nombre"], name="ventas_lact_nombre_cf08e3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=3)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "moneda",
                "verbose_name_plural": "monedas",
                "ordering": ["sigla"],
                "indexes": [
                    models.Index(fields=["sigla"], name="ventas_mone_sigla_e4d382_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=400)),
                ("producto", models.CharField(max_length=200)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        default="ventas/defecto.jpg",
                        null=True,
                        upload_to="ventas/",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id_departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="ventas.departamentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["producto"],
            },
        ),
        migrations.CreateModel(
            name="Tipo_cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("siglas", models.CharField(max_length=2)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "tipo_cuenta",
                "verbose_name_plural": "tipo_cuentas",
                "ordering": ["tipo"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_tipo_id_b6fdab_idx"),
                    models.Index(fields=["tipo"], name="ventas_tipo_tipo_5bfd92_idx"),
                    models.Index(
                        fields=["update_at"], name="ventas_tipo_update__dd033c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contador_billete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("un_peso", models.IntegerField(blank=True, default=0, null=True)),
                ("tres_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("cinco_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("diez_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("veinte_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cincuenta_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cien_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "doscientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "quinientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("mil_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("total", models.IntegerField()),
                ("sub_total", models.IntegerField()),
                ("historia", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo_cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tipos_cuentas",
                        to="ventas.tipo_cuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "contador_billete",
                "verbose_name_plural": "contador_billetes",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField()),
                ("venta", models.FloatField()),
                ("costo", models.FloatField()),
                ("calculo", models.FloatField()),
                ("fecha", models.DateTimeField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="ventas.productos",
                    ),
                ),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "ordering": ["fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="productos",
            index=models.Index(fields=["id"], name="ventas_prod_id_f6485c_idx"),
        ),
        migrations.AddIndex(
            model_name="productos",
            index=models.Index(fields=["codigo"], name="ventas_prod_codigo_8f6a90_idx"),
        ),
        migrations.AddIndex(
            model_name="productos",
            index=models.Index(
                fields=["producto"], name="ventas_prod_product_98c071_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contador_billete",
            index=models.Index(fields=["id"], name="ventas_cont_id_d4413c_idx"),
        ),
        migrations.AddIndex(
            model_name="contador_billete",
            index=models.Index(fields=["fecha"], name="ventas_cont_fecha_54cb31_idx"),
        ),
        migrations.AddIndex(
            model_name="contador_billete",
            index=models.Index(
                fields=["comentario"], name="ventas_cont_comenta_eac935_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contador_billete",
            index=models.Index(fields=["total"], name="ventas_cont_total_e1858a_idx"),
        ),
        migrations.AddIndex(
            model_name="ventas",
            index=models.Index(fields=["id"], name="ventas_vent_id_6918a6_idx"),
        ),
        migrations.AddIndex(
            model_name="ventas",
            index=models.Index(fields=["fecha"], name="ventas_vent_fecha_ef75da_idx"),
        ),
        migrations.AddIndex(
            model_name="ventas",
            index=models.Index(
                fields=["id_producto"], name="ventas_vent_id_prod_9ca7d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ventas",
            index=models.Index(
                fields=["calculo"], name="ventas_vent_calculo_d50391_idx"
            ),
        ),
    ]
