# Generated by Django 5.2 on 2025-09-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Moneda",
        ),
    ]
