# Generated by Django 5.1.3 on 2024-12-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departamentos",
            options={
                "ordering": ["id"],
                "verbose_name": "departmento",
                "verbose_name_plural": "departmentos",
            },
        ),
        migrations.CreateModel(
            name="fileUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
            ],
            options={
                "ordering": ["fecha"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_file_id_19ee8d_idx"),
                    models.Index(fields=["fecha"], name="ventas_file_fecha_fda7df_idx"),
                ],
            },
        ),
    ]
