# Generated by Django 5.2 on 2025-10-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_delete_moneda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=3)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "moneda",
                "verbose_name_plural": "monedas",
                "ordering": ["sigla"],
                "indexes": [
                    models.Index(fields=["sigla"], name="ventas_mone_sigla_e4d382_idx")
                ],
            },
        ),
    ]
