# Generated by Django 5.2 on 2025-10-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_moneda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contador_billete",
            name="historia",
        ),
        migrations.AddField(
            model_name="contador_billete",
            name="moneda",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="monedas",
                to="ventas.moneda",
            ),
        ),
    ]
