# Generated by Django 5.2 on 2025-10-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0004_remove_contador_billete_historia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="moneda",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="monedass",
                to="ventas.moneda",
            ),
        ),
    ]
