# Generated by Django 5.1.4 on 2025-01-04 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_departamentos_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupdate",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileupdate",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
