# Generated by Django 5.1.4 on 2025-01-12 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0006_fileupdate_create_at_fileupdate_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupdate",
            name="archivo",
            field=models.FileField(default=1, upload_to="ficheros/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileupdate",
            name="nombre",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
