# Generated by Django 5.1.4 on 2025-01-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0007_fileupdate_archivo_fileupdate_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileupdate",
            name="nombre",
        ),
    ]
