# Generated by Django 5.1.4 on 2025-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0008_remove_fileupdate_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupdate",
            name="actualizar",
            field=models.BooleanField(default=False),
        ),
    ]
