# Generated by Django 5.1.4 on 2025-01-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0010_departamentos_punto_de_venta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contador_billete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("un_peso", models.IntegerField()),
                ("tres_pesos", models.IntegerField()),
                ("cinco_pesos", models.IntegerField()),
                ("diez_pesos", models.IntegerField()),
                ("veinte_pesos", models.IntegerField()),
                ("cincuenta_pesos", models.IntegerField()),
                ("cien_pesos", models.IntegerField()),
                ("quinientos_pesos", models.IntegerField()),
                ("mil_pesos", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
            options={
                "verbose_name": "contador_billete",
                "verbose_name_plural": "contador_billetes",
                "ordering": ["fecha"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_cont_id_d4413c_idx"),
                    models.Index(fields=["fecha"], name="ventas_cont_fecha_54cb31_idx"),
                    models.Index(
                        fields=["comentario"], name="ventas_cont_comenta_eac935_idx"
                    ),
                    models.Index(fields=["total"], name="ventas_cont_total_e1858a_idx"),
                ],
            },
        ),
    ]
