# Generated by Django 5.1.4 on 2025-01-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0011_contador_billete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contador_billete",
            name="cien_pesos",
        ),
    ]
