# Generated by Django 5.1.4 on 2025-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0012_remove_contador_billete_cien_pesos"),
    ]

    operations = [
        migrations.AddField(
            model_name="contador_billete",
            name="cien_pesos",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contador_billete",
            name="doscientos_pesos",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
