# Generated by Django 5.1.4 on 2025-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0013_contador_billete_cien_pesos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contador_billete",
            name="cien_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="cinco_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="cincuenta_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="diez_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="doscientos_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="mil_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="quinientos_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="tres_pesos",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="un_peso",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contador_billete",
            name="veinte_pesos",
            field=models.IntegerField(default=0),
        ),
    ]
