# Generated by Django 5.1.4 on 2025-02-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0016_alter_contador_billete_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lacteos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_lact_id_203fb4_idx"),
                    models.Index(
                        fields=["nombre"], name="ventas_lact_nombre_cf08e3_idx"
                    ),
                ],
            },
        ),
    ]
