# Generated by Django 5.1.4 on 2025-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_lacteos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lacteos',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Lactetos'},
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
