# Generated by Django 5.1.5 on 2025-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_alter_lacteos_options_alter_lacteos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=400),
        ),
    ]
