# Generated by Django 5.2 on 2025-04-17 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0019_alter_productos_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contador_billete",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contador_billete",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuenta", models.CharField(max_length=100)),
                ("saldo", models.FloatField()),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cuentas",
                "verbose_name_plural": "cuentas",
                "ordering": ["cuenta"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_cuen_id_7a7487_idx"),
                    models.Index(
                        fields=["cuenta"], name="ventas_cuen_cuenta_cd5991_idx"
                    ),
                    models.Index(
                        fields=["update_at"], name="ventas_cuen_update__fd8703_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tipo_cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("comentario", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "tipo_cuenta",
                "verbose_name_plural": "tipo_cuentas",
                "ordering": ["tipo"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_tipo_id_b6fdab_idx"),
                    models.Index(fields=["tipo"], name="ventas_tipo_tipo_5bfd92_idx"),
                    models.Index(
                        fields=["update_at"], name="ventas_tipo_update__dd033c_idx"
                    ),
                ],
            },
        ),
    ]
