# Generated by Django 5.2 on 2025-04-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0020_contador_billete_create_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contador_billete",
            name="tipo_cuenta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipo_cuenta",
                to="ventas.tipo_cuenta",
            ),
            preserve_default=False,
        ),
    ]
