# Generated by Django 5.2 on 2025-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0021_contador_billete_tipo_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipo_cuenta",
            name="siglas",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
