# Generated by Django 5.2 on 2025-04-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0022_tipo_cuenta_siglas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contador_billete",
            options={
                "verbose_name": "contador_billete",
                "verbose_name_plural": "contador_billetes",
            },
        ),
    ]
