# Generated by Django 5.2 on 2025-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_alter_contador_billete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador_billete',
            name='sub_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cien_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cinco_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cincuenta_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='diez_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='doscientos_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='mil_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='quinientos_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tres_pesos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='un_peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='veinte_pesos',
            field=models.IntegerField(default=0),
        ),
    ]
