# Generated by Django 5.2 on 2025-05-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0024_contador_billete_sub_total_cuenta_cien_pesos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contador_billete",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "contador_billete",
                "verbose_name_plural": "contador_billetes",
            },
        ),
        migrations.AlterModelOptions(
            name="departamentos",
            options={
                "ordering": ["id"],
                "verbose_name": "departamento",
                "verbose_name_plural": "departamentos",
            },
        ),
    ]
