# Generated by Django 5.2 on 2025-06-03 20:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_contador_billete_sub_total_cuenta_cien_pesos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contador_billete',
            options={'ordering': ['-fecha'], 'verbose_name': 'contador_billete', 'verbose_name_plural': 'contador_billetes'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cien_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cinco_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cincuenta_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='diez_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='doscientos_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='mil_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='quinientos_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tres_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='un_peso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='veinte_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
