# Generated by Django 5.2 on 2025-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_alter_contador_billete_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cien_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cinco_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cincuenta_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='diez_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='doscientos_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='mil_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='quinientos_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tres_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='un_peso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='veinte_pesos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
