# Generated by Django 5.2 on 2025-06-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_alter_contador_billete_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentos',
            options={'ordering': ['id'], 'verbose_name': 'departamento', 'verbose_name_plural': 'departamentos'},
        ),
        migrations.AlterModelOptions(
            name='fileupdate',
            options={'ordering': ['-fecha']},
        ),
    ]
