# Generated by Django 5.2 on 2025-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0028_alter_departamentos_options_alter_fileupdate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contador_billete",
            name="historia",
            field=models.BooleanField(default=False),
        ),
    ]
