# Generated by Django 5.2 on 2025-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0029_contador_billete_historia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuenta_historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("un_peso", models.IntegerField(blank=True, default=0, null=True)),
                ("tres_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("cinco_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("diez_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("veinte_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cincuenta_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("cien_pesos", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "doscientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "quinientos_pesos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("mil_pesos", models.IntegerField(blank=True, default=0, null=True)),
                ("total", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cuenta_historico",
                "verbose_name_plural": "cuentas_historico",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["id"], name="ventas_cuen_id_0c6ab6_idx"),
                    models.Index(fields=["fecha"], name="ventas_cuen_fecha_3e7e89_idx"),
                    models.Index(fields=["total"], name="ventas_cuen_total_9e9e7d_idx"),
                ],
            },
        ),
    ]
