# Generated by Django 5.2 on 2025-07-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0030_cuenta_historico"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cuenta_historico",
            name="ventas_cuen_total_9e9e7d_idx",
        ),
        migrations.RenameField(
            model_name="cuenta_historico",
            old_name="total",
            new_name="saldo",
        ),
        migrations.AddIndex(
            model_name="cuenta_historico",
            index=models.Index(fields=["saldo"], name="ventas_cuen_saldo_1f8796_idx"),
        ),
    ]
