# Generated by Django 5.2 on 2025-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ventas",
            "0031_remove_cuenta_historico_ventas_cuen_total_9e9e7d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta_historico",
            name="saldo",
            field=models.FloatField(),
        ),
    ]
