# Generated by Django 5.1.4 on 2024-12-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("comantario", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_depa_id_e3f7d6_idx"),
                    models.Index(
                        fields=["nombre"], name="nomina_depa_nombre_a6b4ef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="nomina.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario", models.FloatField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajdores",
                        to="nomina.trabajador",
                    ),
                ),
            ],
            options={
                "ordering": ["trabajador"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_nomi_id_9b223a_idx"),
                    models.Index(
                        fields=["trabajador"], name="nomina_nomi_trabaja_b93f61_idx"
                    ),
                    models.Index(
                        fields=["salario"], name="nomina_nomi_salario_a9b30d_idx"
                    ),
                ],
            },
        ),
    ]
