# Generated by Django 5.2 on 2025-07-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=255)),
                ("comentario", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["cargo"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_carg_id_649559_idx"),
                    models.Index(fields=["cargo"], name="nomina_carg_cargo_46e9da_idx"),
                    models.Index(
                        fields=["activo"], name="nomina_carg_activo_f78264_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DepartamentoNom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departamento", models.CharField(max_length=255)),
                ("comentario", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["departamento"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_depa_id_36681f_idx"),
                    models.Index(
                        fields=["departamento"], name="nomina_depa_departa_d6a3b6_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="nomina_depa_activo_f894c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="nomina.cargo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="nomina.departamentonom",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario", models.FloatField()),
                ("fecha", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajdores",
                        to="nomina.trabajador",
                    ),
                ),
            ],
            options={
                "ordering": ["trabajador"],
            },
        ),
        migrations.CreateModel(
            name="Trabajador2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("salario", models.FloatField()),
                ("fecha_entrada", models.DateField()),
                ("activo", models.BooleanField(blank=True, default=True, null=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_trab_id_dd2be3_idx"),
                    models.Index(
                        fields=["nombre"], name="nomina_trab_nombre_f393d3_idx"
                    ),
                    models.Index(
                        fields=["fecha_entrada"], name="nomina_trab_fecha_e_53d33a_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="nomina_trab_activo_4686ea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Nomina2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajdores",
                        to="nomina.trabajador2",
                    ),
                ),
            ],
            options={
                "ordering": ["trabajador"],
            },
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["id"], name="nomina_trab_id_15f51c_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["nombre"], name="nomina_trab_nombre_4c00a3_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(
                fields=["departamento"], name="nomina_trab_departa_9cbc76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["cargo"], name="nomina_trab_cargo_i_6d4243_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["activo"], name="nomina_trab_activo_db84b1_idx"),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(fields=["id"], name="nomina_nomi_id_9b223a_idx"),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(
                fields=["trabajador"], name="nomina_nomi_trabaja_b93f61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(
                fields=["salario"], name="nomina_nomi_salario_a9b30d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(fields=["activo"], name="nomina_nomi_activo_377e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="nomina2",
            index=models.Index(fields=["id"], name="nomina_nomi_id_1482cb_idx"),
        ),
        migrations.AddIndex(
            model_name="nomina2",
            index=models.Index(
                fields=["trabajador"], name="nomina_nomi_trabaja_81550f_idx"
            ),
        ),
    ]
