# Generated by Django 5.1.4 on 2024-12-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departamento",
            new_name="DepartamentoNom",
        ),
        migrations.RenameIndex(
            model_name="departamentonom",
            new_name="nomina_depa_id_36681f_idx",
            old_name="nomina_depa_id_e3f7d6_idx",
        ),
        migrations.RenameIndex(
            model_name="departamentonom",
            new_name="nomina_depa_nombre_851fa6_idx",
            old_name="nomina_depa_nombre_a6b4ef_idx",
        ),
    ]
