# Generated by Django 5.1.4 on 2024-12-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0002_rename_departamento_departamentonom_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="departamentonom",
            old_name="comantario",
            new_name="comentario",
        ),
    ]
