# Generated by Django 5.1.4 on 2024-12-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0003_rename_comantario_departamentonom_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("comentario", models.TextField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_carg_id_649559_idx"),
                    models.Index(
                        fields=["nombre"], name="nomina_carg_nombre_6bd8a7_idx"
                    ),
                ],
            },
        ),
    ]
