# Generated by Django 5.1.4 on 2024-12-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0004_cargo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departamentonom",
            options={"ordering": ["departamento"]},
        ),
        migrations.RemoveIndex(
            model_name="departamentonom",
            name="nomina_depa_nombre_851fa6_idx",
        ),
        migrations.RenameField(
            model_name="departamentonom",
            old_name="nombre",
            new_name="departamento",
        ),
        migrations.AddIndex(
            model_name="departamentonom",
            index=models.Index(
                fields=["departamento"], name="nomina_depa_departa_d6a3b6_idx"
            ),
        ),
    ]
