# Generated by Django 5.1.4 on 2024-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0005_alter_departamentonom_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={"ordering": ["cargo"]},
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="nomina_carg_nombre_6bd8a7_idx",
        ),
        migrations.AddField(
            model_name="cargo",
            name="cargo",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["cargo"], name="nomina_carg_cargo_46e9da_idx"),
        ),
    ]
