# Generated by Django 5.1.4 on 2024-12-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0006_alter_cargo_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="cargo",
            name="cargo",
            field=models.CharField(max_length=255),
        ),
    ]
