# Generated by Django 5.1.4 on 2025-01-01 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0008_trabajador_cargo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trabajador",
            options={"ordering": ["nombre"]},
        ),
        migrations.AddField(
            model_name="trabajador",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["activo"], name="nomina_carg_activo_f78264_idx"),
        ),
        migrations.AddIndex(
            model_name="departamentonom",
            index=models.Index(fields=["activo"], name="nomina_depa_activo_f894c7_idx"),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(fields=["activo"], name="nomina_nomi_activo_377e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["id"], name="nomina_trab_id_15f51c_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["nombre"], name="nomina_trab_nombre_4c00a3_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(
                fields=["departamento"], name="nomina_trab_departa_9cbc76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["cargo"], name="nomina_trab_cargo_i_6d4243_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["activo"], name="nomina_trab_activo_db84b1_idx"),
        ),
    ]
