# Generated by Django 5.1.4 on 2025-01-01 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0009_alter_trabajador_options_trabajador_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomina",
            name="fecha",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 1, 19, 50, 47, 335007, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
