# Generated by Django 5.1.5 on 2025-03-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0010_nomina_fecha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trabajador2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("salario", models.FloatField()),
                ("fecha_entrada", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_trab_id_dd2be3_idx"),
                    models.Index(
                        fields=["nombre"], name="nomina_trab_nombre_f393d3_idx"
                    ),
                    models.Index(
                        fields=["fecha_entrada"], name="nomina_trab_fecha_e_53d33a_idx"
                    ),
                    models.Index(
                        fields=["activo"], name="nomina_trab_activo_4686ea_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Nomina2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trabajdores",
                        to="nomina.trabajador2",
                    ),
                ),
            ],
            options={
                "ordering": ["trabajador"],
                "indexes": [
                    models.Index(fields=["id"], name="nomina_nomi_id_1482cb_idx"),
                    models.Index(
                        fields=["trabajador"], name="nomina_nomi_trabaja_81550f_idx"
                    ),
                ],
            },
        ),
    ]
