# Generated by Django 5.1.5 on 2025-03-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0011_trabajador2_nomina2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador2",
            name="activo",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
