# Generated by Django 5.1.5 on 2025-03-29 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0012_alter_trabajador2_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador2",
            name="fecha_baja",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
