# Generated by Django 5.1.5 on 2025-03-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomina", "0013_trabajador2_fecha_baja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador2",
            name="fecha_baja",
            field=models.DateField(blank=True, null=True),
        ),
    ]
