# Generated by Django 5.2 on 2025-07-19 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unidad_medida", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
            },
        ),
        migrations.CreateModel(
            name="ProcesoProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("en_proceso", "En Proceso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="iniciado",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Proceso de Producción",
                "verbose_name_plural": "Procesos de Producción",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="EntradaProduccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produc_proceso.material",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produc_proceso.procesoproduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Producción",
                "verbose_name_plural": "Entradas de Producción",
            },
        ),
        migrations.AddField(
            model_name="procesoproduccion",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="produc_proceso.producto",
            ),
        ),
    ]
