# Generated by Django 5.2 on 2025-05-28 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("stock_actual", models.PositiveIntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_ee71ed_idx"),
                    models.Index(
                        fields=["nombre"], name="produccion__nombre_c29428_idx"
                    ),
                    models.Index(
                        fields=["stock_actual"], name="produccion__stock_a_f91d38_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["producto"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_aa3318_idx"),
                    models.Index(
                        fields=["producto"], name="produccion__product_a98346_idx"
                    ),
                    models.Index(
                        fields=["cantidad"], name="produccion__cantida_b27ebd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("destino", models.CharField(max_length=255)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "salida",
                "verbose_name_plural": "salidas",
                "ordering": ["producto"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_0f959c_idx"),
                    models.Index(
                        fields=["producto"], name="produccion__product_801f00_idx"
                    ),
                    models.Index(
                        fields=["cantidad"], name="produccion__cantida_5cd65b_idx"
                    ),
                ],
            },
        ),
    ]
