# Generated by Django 5.2 on 2025-07-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_fe3dbf_idx"),
                    models.Index(
                        fields=["nombre"], name="produccion__nombre_fbd9c3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_639f8c_idx"),
                    models.Index(
                        fields=["nombre"], name="produccion__nombre_e00433_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("stock_actual", models.PositiveIntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produccion.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "produccion",
                "verbose_name_plural": "produccion",
                "ordering": ["producto"],
            },
        ),
        migrations.CreateModel(
            name="Salida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.destino",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produccion.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "salida",
                "verbose_name_plural": "salidas",
                "ordering": ["producto"],
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["id"], name="produccion__id_ee71ed_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="produccion__nombre_c29428_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["stock_actual"], name="produccion__stock_a_f91d38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produccion",
            index=models.Index(fields=["id"], name="produccion__id_aa3318_idx"),
        ),
        migrations.AddIndex(
            model_name="produccion",
            index=models.Index(
                fields=["producto"], name="produccion__product_a98346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produccion",
            index=models.Index(
                fields=["cantidad"], name="produccion__cantida_b27ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(fields=["id"], name="produccion__id_0f959c_idx"),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["producto"], name="produccion__product_801f00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["cantidad"], name="produccion__cantida_5cd65b_idx"
            ),
        ),
    ]
