# Generated by Django 5.2 on 2025-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0002_categoria_alter_producto_categoria"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produccion",
            options={
                "ordering": ["producto"],
                "verbose_name": "produccion",
                "verbose_name_plural": "produccion",
            },
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Destino",
                "verbose_name_plural": "Destinos",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="produccion__id_639f8c_idx"),
                    models.Index(
                        fields=["nombre"], name="produccion__nombre_e00433_idx"
                    ),
                ],
            },
        ),
    ]
