# Generated by Django 5.2 on 2025-05-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0003_alter_produccion_options_destino"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salida",
            name="destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="produccion.destino"
            ),
        ),
    ]
