# Generated by Django 5.1.4 on 2025-01-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pepe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="punto_venta_id_24076e_idx"),
                    models.Index(
                        fields=["nombre"], name="punto_venta_nombre_e10164_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="punto_venta_id_6f7632_idx"),
                    models.Index(
                        fields=["nombre"], name="punto_venta_nombre_208517_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="punto_venta_id_9af91b_idx"),
                    models.Index(
                        fields=["nombre"], name="punto_venta_nombre_fb5659_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("contacto", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.IntegerField(blank=True, null=True)),
                ("correo", models.CharField(blank=True, max_length=150, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proveedore",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="punto_venta_id_4db25e_idx"),
                    models.Index(
                        fields=["nombre"], name="punto_venta_nombre_01937d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.PositiveIntegerField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.categoria",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PuntoDeVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Punto_de_Venta",
                "verbose_name_plural": "Puntos_de_Ventas",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="punto_venta_id_af424c_idx"),
                    models.Index(
                        fields=["nombre"], name="punto_venta_nombre_fb774f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.almacen",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.producto",
                    ),
                ),
                (
                    "punto_de_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.puntodeventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
                "ordering": ["producto"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.producto",
                    ),
                ),
                (
                    "punto_de_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="punto_venta.puntodeventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["producto"],
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["id"], name="punto_venta_id_a2b48e_idx"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="punto_venta_nombre_c36064_idx"),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(fields=["id"], name="punto_venta_id_28f7a9_idx"),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["producto"], name="punto_venta_product_4f593f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(
                fields=["punto_de_venta"], name="punto_venta_punto_d_34b4a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(fields=["fecha"], name="punto_venta_fecha_659e27_idx"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["id"], name="punto_venta_id_021761_idx"),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["producto"], name="punto_venta_product_c8aea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["punto_de_venta"], name="punto_venta_punto_d_5628d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(fields=["fecha"], name="punto_venta_fecha_77963e_idx"),
        ),
    ]
