# Generated by Django 5.2 on 2025-07-19 20:06

import compras.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "negocio",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "ci",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[compras.models.Cliente.validar_longitud_11_digitos],
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre", "apellido"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=250, unique=True),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio", models.FloatField()),
                ("stock", models.PositiveIntegerField(default=0)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Almacen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "almacen",
                "verbose_name_plural": "almacenes",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="compras_alm_id_bbef01_idx"),
                    models.Index(
                        fields=["nombre"], name="compras_alm_nombre_347c3c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=255)),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
                "ordering": ["producto"],
                "indexes": [
                    models.Index(fields=["id"], name="compras_com_id_1b41b4_idx"),
                    models.Index(
                        fields=["producto"], name="compras_com_product_5cc5e7_idx"
                    ),
                    models.Index(
                        fields=["cantidad"], name="compras_com_cantida_9b9242_idx"
                    ),
                    models.Index(fields=["fecha"], name="compras_com_fecha_49ff0e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("c", "Compra"), ("v", "Venta")],
                        default="c",
                        max_length=1,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("pagada-eleventa", "Pagada y registrada en Eleventa"),
                            ("anulada", "Anulada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.FloatField(default=0)),
                ("cantidad_producto", models.IntegerField(default=0)),
                ("bonificacion", models.FloatField(default=0)),
                ("total", models.FloatField(default=0)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="compras.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="PrecioProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "precio-producto",
                "verbose_name_plural": "precios-productos",
                "ordering": ["producto"],
                "indexes": [
                    models.Index(fields=["id"], name="compras_pre_id_f95bdb_idx"),
                    models.Index(
                        fields=["producto"], name="compras_pre_product_92b627_idx"
                    ),
                    models.Index(
                        fields=["precio"], name="compras_pre_precio_3b600c_idx"
                    ),
                    models.Index(fields=["fecha"], name="compras_pre_fecha_a77a1e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "precio_unitario",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "subtotal",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.factura",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas_usado",
                        to="compras.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Factura",
                "verbose_name_plural": "Detalles de Facturas",
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "unidad_medida",
                "verbose_name_plural": "unidades_medidas",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["id"], name="compras_uni_id_2b4a58_idx"),
                    models.Index(
                        fields=["nombre"], name="compras_uni_nombre_c425ec_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="unidadmedida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="compras.unidadmedida"
            ),
        ),
    ]
