# Generated by Django 5.1.3 on 2024-12-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "compras",
            "0003_almacen_create_at_almacen_update_at_compra_create_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="productos_compras/"),
        ),
    ]
