# Generated by Django 5.1.3 on 2024-12-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0008_unidadmedida"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="medida",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="compras.unidadmedida",
            ),
            preserve_default=False,
        ),
    ]
