# Generated by Django 5.2 on 2025-04-30 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0009_producto_medida"),
        ("ventas", "0024_contador_billete_sub_total_cuenta_cien_pesos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="almacen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventas.departamentos"
            ),
        ),
    ]
