# Generated by Django 5.2 on 2025-05-07 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0010_alter_producto_almacen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=200)),
                ("documento", models.CharField(max_length=20, unique=True)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre", "apellido"],
            },
        ),
        migrations.CreateModel(
            name="DetalleFactura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Detalle de Factura",
                "verbose_name_plural": "Detalles de Facturas",
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "fecha_emision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("pagada-eleventa", "Pagada y registrada en Eleventa"),
                            ("anulada", "Anulada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="compras_pro_id_ee51d2_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="compras_pro_nombre_ac0b59_idx",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="update_at",
            new_name="fecha_actualizacion",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="create_at",
            new_name="fecha_registro",
        ),
        migrations.RenameIndex(
            model_name="compra",
            new_name="compras_com_product_5cc5e7_idx",
            old_name="compras_com_product_de9e7b_idx",
        ),
        migrations.RenameIndex(
            model_name="precioproducto",
            new_name="compras_pre_product_92b627_idx",
            old_name="compras_pre_product_9e5166_idx",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="almacen",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="medida",
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo",
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidadmedida",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="compras.unidadmedida",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compra",
            name="producto",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="precioproducto",
            name="producto",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="detallefactura",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="compras.producto"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas",
                to="compras.cliente",
            ),
        ),
        migrations.AddField(
            model_name="detallefactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="compras.factura",
            ),
        ),
    ]
