# Generated by Django 5.2 on 2025-05-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0011_cliente_detallefactura_factura_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="documento",
        ),
    ]
