# Generated by Django 5.2 on 2025-05-08 00:49

import compras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0012_remove_cliente_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ci",
            field=models.IntegerField(
                default=11111111111,
                validators=[compras.models.Cliente.validar_longitud_11_digitos],
            ),
            preserve_default=False,
        ),
    ]
