# Generated by Django 5.2 on 2025-05-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0013_cliente_ci"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="bonificaion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
