# Generated by Django 5.2 on 2025-05-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0014_factura_bonificaion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="bonificaion",
            new_name="bonificacion",
        ),
    ]
