# Generated by Django 5.2 on 2025-05-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_rename_bonificaion_factura_bonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='negocio',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
