# Generated by Django 5.2 on 2025-05-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0016_cliente_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="negocio",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
