# Generated by Django 5.2 on 2025-05-20 22:31

import compras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_alter_cliente_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.IntegerField(blank=True, null=True, validators=[compras.models.Cliente.validar_longitud_11_digitos]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='negocio',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
