# Generated by Django 5.2 on 2025-05-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_alter_cliente_apellido_alter_cliente_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('c', 'Compra'), ('v', 'Venta')], default='v', max_length=1),
        ),
    ]
