# Generated by Django 5.2 on 2025-05-28 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_factura_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('director', models.CharField(max_length=255)),
                ('dirección', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Datos de la Entidad',
                'verbose_name_plural': 'Datos de la Entidad',
            },
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
