# Generated by Django 5.2 on 2025-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_entidad_alter_detallefactura_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
