# Generated by Django 5.2 on 2025-06-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0020_alter_detallefactura_cantidad_alter_factura_tipo"),
        ("compras", "0021_alter_detallefactura_precio_unitario"),
    ]

    operations = []
