# Generated by Django 5.2 on 2025-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_alter_detallefactura_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('c', 'Compra'), ('v', 'Venta')], default='c', max_length=1),
        ),
    ]
