# Generated by Django 5.2 on 2025-06-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_alter_detallefactura_cantidad_alter_factura_tipo'),
        ('compras', '0025_alter_producto_precio'),
    ]

    operations = [
    ]
