# Generated by Django 5.2 on 2025-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_alter_detallefactura_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='bonificacion',
            field=models.FloatField(default=0),
        ),
    ]
