# Generated by Django 5.2 on 2025-06-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_merge_20250531_2313'),
        ('compras', '0028_alter_factura_bonificacion'),
    ]

    operations = [
    ]
