# Generated by Django 5.2 on 2025-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0029_merge_20250603_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(editable=False, max_length=250, unique=True),
        ),
    ]
