# Generated by Django 5.2 on 2025-06-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0030_alter_producto_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallefactura",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detallefactura",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detallefactura",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
