# Generated by Django 5.2 on 2025-06-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_merge_20250603_1719'),
        ('compras', '0031_alter_detallefactura_cantidad_and_more'),
    ]

    operations = [
    ]
