# Generated by Django 5.2 on 2025-06-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0032_factura_cantidad_producto"),
        ("compras", "0032_merge_20250612_1521"),
    ]

    operations = []
