# Generated by Django 5.2 on 2025-06-20 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0033_merge_20250618_1610"),
        ("compras", "0033_merge_20250618_1939"),
        ("compras", "0034_merge_20250618_1322"),
    ]

    operations = []
