# Generated by Django 5.2 on 2025-07-02 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0035_merge_20250620_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallefactura",
            name="cantidad",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
