# Generated by Django 5.2 on 2025-07-07 23:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0035_merge_20250620_1954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallefactura",
            name="cantidad",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="detallefactura",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas_usado",
                to="compras.producto",
            ),
        ),
    ]
