# Generated by Django 5.2 on 2025-07-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estadisticas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipos",
                    models.CharField(
                        choices=[
                            ("s", "Semanal"),
                            ("M", "Mensual"),
                            ("T", "Trimestral"),
                            ("S", "Semestral"),
                            ("A", "Anual"),
                        ],
                        max_length=1,
                    ),
                ),
                ("periodo", models.CharField(max_length=100)),
                ("total_vendido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ResumenVenta",
                "verbose_name_plural": "ResumenVentas",
                "ordering": ["fecha_actualizacion"],
                "indexes": [
                    models.Index(fields=["id"], name="resumen_est_id_c07a8a_idx"),
                    models.Index(
                        fields=["fecha_actualizacion"],
                        name="resumen_est_fecha_a_679408_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResumenVentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=100)),
                ("total_vendido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ResumenVenta",
                "verbose_name_plural": "ResumenVentas",
                "ordering": ["fecha_actualizacion"],
                "indexes": [
                    models.Index(fields=["id"], name="resumen_res_id_b039db_idx"),
                    models.Index(
                        fields=["fecha_actualizacion"],
                        name="resumen_res_fecha_a_a2897b_idx",
                    ),
                ],
            },
        ),
    ]
